### ISSUE TITLE
Not working after last commits

### ISSUE THREAD

**Issue by sattellite** [spadgos/sublime-ToggleQuotes#14]
Have this error in SublimeText console:

```
Traceback (most recent call last):
  File "/usr/local/sublime_text_3/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "toggle_quotes in /home/sattellite/.config/sublime-text-3/Installed Packages/ToggleQuotes.sublime-package", line 27, in run
KeyError: 'key'
```

`kwargs` is empty.

**Comment by robcrocombe** [comment]
Have you overridden your sublime-keymap for this plugin? `kwargs` is provided by a key binding argument.

**Comment by sattellite** [comment]
Yes, I have taken a new keymap from the repository and added to the user keymap.

**Comment by robcrocombe** [comment]
Ah, I understand. I never used that behaviour of the plugin before so I must have missed it when writing the backquote feature. I have written a new PR (#15) which should do as you suggest - cycle between all three quote styles.

**Comment by robcrocombe** [comment]
@sattellite does this fix your issue?

**Comment by sattellite** [comment]
@robcrocombe yes, thank you
